apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontback
spec:
  destination:
    name: back
  sources:
    - name: front
      namespace: apps
      action: allow