apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: deny-all
spec:
  destination:
    name: "*"
    namespace: apps
  sources:
    - name: "*"
      namespace: apps
      action: deny